### ISSUE TITLE
虚拟天线索引

### ISSUE THREAD

**Issue by itshsiao** [Aiuan/TI-Radar-Processing#2]
hi 同学您好，请问您在生成距离角度热图的过程中是如何确定选取的水平分布的86个虚拟天线索引的？（1; 2; 3; 4; 17; ...... 128; 141; 142; 143; 144）。感谢您的帮助！

**Comment by Aiuan** [comment]
1、TI文档中有详细的阵面说明
2、mmWave Studio原始的MATLAB例程中也有相应的代码片段
![image](https://github.com/Aiuan/TI-Radar-Processing/assets/47709353/6a3d0324-4030-445b-85a2-c920f3aeb65f)
![image](https://github.com/Aiuan/TI-Radar-Processing/assets/47709353/928b6977-d78a-42fe-a072-0c6a8c4a8036)
![image](https://github.com/Aiuan/TI-Radar-Processing/assets/47709353/21586d26-b01e-47c4-903e-da8e4fc406a7)

**Comment by itshsiao** [comment]
好的好的，请问可以加个微信联系一下吗？老师让我做这个东西实在是无从下手，想咨询您一些关于级联雷达的问题，非常感谢您的帮助！我的邮箱是liyang-x@outlook.com。万分感谢！！！

**Comment by Aiuan** [comment]
我的邮箱：fyai@zju.edu.cn
