### ISSUE TITLE
相机与雷达坐标系的标定

### ISSUE THREAD

**Issue by jobosla** [Aiuan/TI-Radar-Processing#3]
您好，同学，最近我也正在学习TI的2243级联板，在学习您的项目的时候，发现在您提供的文件夹中找不到 PhotoPoint.m 和 match_main.m两个脚本文件，可以再提供一下吗，非常感谢！！！我的邮箱是wuqinghui1013@163.com 。

**Comment by Aiuan** [comment]
在哪里看到需要这两个文件？

**Comment by jobosla** [comment]
作者您好，我是在您github，TI-Radar-Processing 工程的README.md中看到的，如下图，在您的文件夹中没有找到PhotoPoint.m 、 match_main.m 和 show.m这三个脚本文件。




     

| |
wuqinghui1013
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Fuyuan ***@***.***> |
| 发送日期 | 2024年5月21日 20:36 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [Aiuan/TI-Radar-Processing] 相机与雷达坐标系的标定 (Issue #3) |

在哪里看到需要这两个文件？

**Comment by Aiuan** [comment]
图片未显示

**Comment by jobosla** [comment]
实在不好意思，刚才试了好久，图片一直上传失败，我给您发了邮箱，麻烦您查收一下

**Comment by Aiuan** [comment]
不好意思，代码没有及时更新，造成文档与代码的不匹配，现已更新，你可以在camera-radar-caliibration文件夹中找到相应的脚本

**Comment by jobosla** [comment]
好的好的，非常感谢！！！
